name: Publish the website

on:
  push:
    branches:
      - main

concurrency: ${{ github.ref }}

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - name: Check out the code 🗄
        uses: actions/checkout@v4

      - uses: ./.github/actions/setup-environment

      - name: Lint the code 🕵
        run: yarn lint:check

      - name: Check the prettiness of the code 💅
        run: yarn format:check

      - name: Build code 🛠
        run: yarn build

      - name: Deploy the demo website 🚀
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          branch: gh-pages
          folder: build/client
